# Generated by Django 5.0.1 on 2024-02-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='keysearch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prosearch',
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
