# Generated by Django 5.0.1 on 2024-03-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_os_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job_type',
            field=models.CharField(choices=[('producer', '기획자'), ('designer', '디자이너'), ('developer', '개발자'), ('others', '기타')], default='OTHERS', max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='year_type',
            field=models.CharField(choices=[('underone', '1년 미만'), ('onetothree', '1년~3년'), ('threetofive', '3년~5년'), ('abovefive', '5년 이상'), ('starter', '취준생')], default='STARTER', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='login_type',
            field=models.CharField(choices=[('kakao', '카카오'), ('google', '구글')], max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='os_type',
            field=models.CharField(choices=[('windows', '윈도우'), ('mac', '맥')], max_length=15),
        ),
    ]
