# Generated by Django 5.0.1 on 2024-02-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_nickname_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key_searcher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pro_searcher',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
