# Generated by Django 5.0.1 on 2024-02-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_key_searcher_user_pro_searcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key_searcher',
            field=models.CharField(blank=True, default='Default key', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='pro_searcher',
            field=models.CharField(blank=True, default='Default pro', max_length=30),
        ),
    ]
