# Generated by Django 5.0.1 on 2024-02-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_key_searcher_alter_user_pro_searcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key_searcher',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='pro_searcher',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
