# Generated by Django 5.0.1 on 2024-02-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_keysearcher_prosearcher_remove_user_key_searcher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='key_searcher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pro_searcher',
        ),
        migrations.DeleteModel(
            name='KeySearcher',
        ),
        migrations.DeleteModel(
            name='ProSearcher',
        ),
    ]
