# Generated by Django 5.0.1 on 2024-02-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_key_searcher_remove_user_pro_searcher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeySearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ProSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='keysearches', to='accounts.keysearch'),
        ),
        migrations.AddField(
            model_name='user',
            name='prosearch',
            field=models.ManyToManyField(blank=True, related_name='prosearches', to='accounts.prosearch'),
        ),
    ]
