# Generated by Django 5.0.1 on 2024-02-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_keysearch_prosearch_user_bookmark_user_prosearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prosearch',
        ),
        migrations.AddField(
            model_name='user',
            name='keysearch',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.DeleteModel(
            name='KeySearch',
        ),
        migrations.DeleteModel(
            name='ProSearch',
        ),
        migrations.AddField(
            model_name='user',
            name='prosearch',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
