# Generated by Django 5.0.1 on 2024-02-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100, verbose_name='플렛폼')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ShortcutKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='카테고리')),
                ('keys', models.CharField(max_length=100, verbose_name='키 조합')),
                ('description', models.TextField(verbose_name='설명')),
                ('platform', models.CharField(max_length=100, verbose_name='플렛폼')),
                ('index', models.IntegerField()),
                ('bookmark', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'ordering': ['-bookmark', '-index'],
            },
        ),
    ]
