# Generated by Django 4.2.9 on 2024-01-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortcutKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='카테고리')),
                ('keys', models.CharField(max_length=100, verbose_name='키 조합')),
                ('description', models.TextField(verbose_name='설명')),
                ('platform', models.TextField(verbose_name='플렛폼')),
            ],
        ),
    ]
