# Generated by Django 4.2.9 on 2024-01-31 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcuts', '0003_shortcutkey_bookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortcutkey',
            options={'ordering': ['-bookmark', '-index']},
        ),
    ]
