# Generated by Django 4.2.9 on 2024-02-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcuts', '0004_alter_shortcutkey_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100, verbose_name='플렛폼')),
                ('image', models.TextField(verbose_name='로고 이미지')),
            ],
        ),
    ]
