# Generated by Django 5.0.1 on 2024-02-02 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcuts', '0005_programlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programlist',
            name='prosearcher',
            field=models.ManyToManyField(blank=True, related_name='pro_searchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shortcutkey',
            name='keysearcher',
            field=models.ManyToManyField(blank=True, related_name='key_searchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
