# Generated by Django 5.0.1 on 2024-02-02 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcuts', '0006_programlist_prosearcher_shortcutkey_keysearcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programlist',
            name='prosearcher',
        ),
        migrations.RemoveField(
            model_name='shortcutkey',
            name='keysearcher',
        ),
    ]
